### ISSUE TITLE
[Bug] js和css资源使用了preload预加载特性的时候，无法正常retry

### ISSUE THREAD

**Issue by Sara2009** [Nikaple/assets-retry#100]
## I'm submitting a...

<pre><code>
[ ] Regression 
[✅] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
当js链接使用link标签进行preload预加载后，只retry了预加载的link标签，而对同一个url的js的script标签没有进行retry，导致js没有重试执行
css链接同样的问题

## Expected behavior
不仅preload的资源retry，同一个url的script或者style标签也能正确retry

## Environment

<pre><code>
Assets-retry version: 0.3.4

 
For Tooling issues:
- Browser version: Google Chrome Version 112.0.5615.137 (Official Build) (arm64)
- Platform:   Mac M1

Others:

</code></pre>

**Comment by Nikaple** [comment]
`link[rel=preload]` 进行重试后，应该只是会增加重试计数吧，在默认的 `maxRetryCount = 3` 的情况下，理论上 `<script>` 也是能重试的。这里如果修改为重试时忽略 `link[rel=preload]` 的元素，是不是就可以了？

**Comment by Sara2009** [comment]
> `link[rel=preload]` 进行重试后，应该只是会增加重试计数吧，在默认的 `maxRetryCount = 3` 的情况下，理论上 `<script>` 也是能重试的。这里如果修改为重试时忽略 `link[rel=preload]` 的元素，是不是就可以了？

确实，maxRetryCount=1的情况下有问题，改成2就可以了，重试时忽略 `link[rel=preload]` 的元素，这个应该怎么配置？

**Comment by Sara2009** [comment]
> `link[rel=preload]` 进行重试后，应该只是会增加重试计数吧，在默认的 `maxRetryCount = 3` 的情况下，理论上 `<script>` 也是能重试的。这里如果修改为重试时忽略 `link[rel=preload]` 的元素，是不是就可以了？

发现对css还是无效，无法正常加载，js在maxRetryCount=2的时候可以加载

**Comment by cobish** [comment]
@Nikaple 作者能否更新一下 npm 包，落后了一个版本
