### ISSUE TITLE
讨论：同步加载资源的异常监听

### ISSUE THREAD

**Issue by ColaQian** [Nikaple/assets-retry#104]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x ] confusion
</code></pre>

同步资源的加载监听核心是通过如下代码实现的
`document.addEventListener('error', errorHandler, true)
    document.addEventListener('load', loadHandler, true)`
想请教的是，这里的监听回调函数是会被同步触发的么？我认知里理解的这些回调函数都是异步触发的，如果是异步触发的，js script 加载异常的场景下，怎么能保证及时拦截并重试加载呢？

@Nikaple  求大佬帮忙解惑，感激不尽。

**Comment by Nikaple** [comment]
拦截了 createElement 等 DOM 方法，具体可看 `retry-async.ts` 源码

**Comment by ColaQian** [comment]
> 拦截了 createElement 等 DOM 方法，具体可看 `retry-async.ts` 源码

大佬，没太get到😭，我的问题应该是对 retry-sync.ts 里的逻辑有疑惑，跟 retry-async.ts 会有关系么？两者会相互影响？主要疑惑点是 `document.addEventListener('error', errorHandler, true); document.addEventListener('load', loadHandler, true) ` 这里errorHandler的触发是如何保证的同步执行的？ 如果是异步触发的，又是如何保证script资源及时被错误重试的（假设script加载error）？

@Nikaple 😭

**Comment by Nikaple** [comment]
分两种情况：
1. 调用方关心script加载状态，例如:
	```js
	new Promise((resolve, reject) => {
	  const script = document.createElement('script');
	  script.onload = resolve;
	  script.onerror = reject;
	})
	```
    这种情况是hook了createElement方法，创建出来的是经过代理的HTMLScriptElement，在代理后的对象中实现了重试逻辑。

2. 调用方不关心script加载状态，例如直接写的script标签：这种才是走到 retry-sync.ts 里的逻辑，通过监听load/error事件来对script进行重试。还有疑问可以 clone 仓库使用 e2e 里的测试用例断点调试

**Comment by ColaQian** [comment]
> 分两种情况：
> 
> 1. 调用方关心script加载状态，例如:
>    ```js
>    new Promise((resolve, reject) => {
>      const script = document.createElement('script');
>      script.onload = resolve;
>      script.onerror = reject;
>    })
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    这种情况是hook了createElement方法，创建出来的是经过代理的HTMLScriptElement，在代理后的对象中实现了重试逻辑。
> 2. 调用方不关心script加载状态，例如直接写的script标签：这种才是走到 retry-sync.ts 里的逻辑，通过监听load/error事件来对script进行重试。还有疑问可以 clone 仓库使用 e2e 里的测试用例断点调试

大佬，你梳理的这两点我都能理解，主要的疑惑点是第2点中的「通过监听load/error事件来对script进行重试」，场景就是直接写的script标签，等于是同步资源的异常加载重试，这里的error事件的回调处理函数是如何保证同步执行的呢，因为对于同步资源加载错误，重试的资源需要在当前错误标签后创建，但是error事件的回调我的理解下又是一个异步执行函数。这块的逻辑冲突不知道怎么绕过去.... @Nikaple

**Comment by Nikaple** [comment]
如果遇到问题，可提供[最小复现案例](https://minimum-reproduction.wtf/)，尽量避免[X-Y问题](https://en.wikipedia.org/wiki/XY_problem)

**Comment by ColaQian** [comment]
> 如果遇到问题，可提供[最小复现案例](https://minimum-reproduction.wtf/)，尽量避免[X-Y问题](https://en.wikipedia.org/wiki/XY_problem)

不不不，大佬，我这边不是遇到问题了，只是对这个同步资源加载的异常处理的逻辑有一些疑问，就是我上面回复的，简单一句总结就是： error 事件的回调函数异步执行是怎么处理加载同步资源的报错的
