### ISSUE TITLE
js重载顺序问题

### ISSUE THREAD

**Issue by ycvcb123** [Nikaple/assets-retry#16]
下面这里不是很明白，如下script的的写法执行顺序是串行同步的，app.js 加载出错的情况下，vendor已经是加载完了，而且，document.createElement 只是创建一个script标签而已，在还是loading的状态下，依旧这样处理会有什么问题？

![image](https://user-images.githubusercontent.com/15381888/71443384-9092fc00-2745-11ea-859e-63eb170c8912.png)

![image](https://user-images.githubusercontent.com/15381888/71442919-195c6880-2743-11ea-9218-31b33a39a8e9.png)

**Comment by Nikaple** [comment]
假设由于网络问题，CDN 中的 `vendor.js` 和 `app.js` 均加载异常，并使用 `document.createElement` 发起重试。
`document.createElement` 虽然可以同步地创建 `script` 标签，但其内容的加载是异步的。假设 vendor.js 需要 5 秒加载，而 `app.js` 只需要 1 秒加载，那么浏览器在 1 秒后，就会执行 app.js 中下载完毕的代码，而在 5 秒后才会执行 `vendor.js` 中的方法。
如果 `app.js` 依赖 `vendor.js` 中暴露的全局方法（如 webpack 打包产生的 vendor_lib ），代码就会报错了。时间线示意图如下：

```
--- 请求 vendor ------------------------------------------- vendor 加载完毕 ----------
--- 请求 app ------ app 加载完毕 --- 执行 app 代码（报错） ----------------------------
```

如果在该场景使用 `document.write` 就没有问题：

```
--- 请求 vendor ---------- vendor 加载完毕 ----- 执行 vendor 代码 ----------------------
--- 请求 app ---- app 加载完毕 ------------------------------------- 执行 app 代码 -----
```
