### ISSUE TITLE
need declaration (.d.ts) file

### ISSUE THREAD

**Issue by milobluebell** [Nikaple/assets-retry#50]
dist里没有声明文件，搞个typing吧

**Comment by Nikaple** [comment]
请问你在项目中是怎么引入的呢？目前推荐的两种方法（内联或webpack），其实都是用不到 typing 的能力的，所以就没打包 typing 了

**Comment by milobluebell** [comment]
嗯嗯 我后来用了内联就不需要声明了。我是用gulp +rollup我们自己写的脚手架，根据自己的约定，会自动将import进来的模块切块打包，并且上传cdn，所以有个import的过程，没有d.ts就会飙红。 后来发现这个脚本不应该上传到cdn，就内联了。
