### ISSUE TITLE
retry-css

### ISSUE THREAD

**Issue by lihaonanGY** [Nikaple/assets-retry#7]
超级赞👍的代码，这两天正好在做这块
我在document.stylesheets时
uncaught DOMException: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules
    at HTMLDocument.<anonymous> 

是您在文档常见问题里说的那个问题么。
在实际应用时是不是会经常出现读不到CSSStyleSheet的情况，就不能正常retrycss，处理背景图这样的问题。

**Comment by Nikaple** [comment]
这里报错是测试时没考虑到跨域 CSS 情况，下个版本会解决这里的报错问题。不过如果要拥有重试背景图的功能的话，还是需要 CDN 正常配置 CORS 头部（这个一般 CDN 都会有配置的），然后在 link 标签上加上 `crossorigin="anonymous"` 就可以正常读到 rules 属性了 :wink:

**Comment by lihaonanGY** [comment]
还有一个小建议：
配置domain的时候 是不是可以配置成几组。
['cdn1','cdn1的备用源,'cdn1的备用源2']
['cdn2','cdn2的备用源]

**Comment by Nikaple** [comment]
使用对象的配置形式就可以了，你这种情况：
```json
{
  "cdn1": "cdn1的备用源",
  "cdn1的备用源": "cdn1的备用源2",
  "cdn1的备用源2": "cdn1",
  "cdn2": "cdn2的备用源",
  "cdn2的备用源": "cdn2"
}
```
