### ISSUE TITLE
dist文件中，带上了sourcemap

### ISSUE THREAD

**Issue by luanwulin** [Nikaple/assets-retry#72]
rt，带上了soucemap，但是目录是相对路径的。webpack无法直接识别，会一直报错

sourceMappingURL=assets-retry.umd.js.map

**Comment by Nikaple** [comment]
webpack 配置可以参考[文档](https://github.com/Nikaple/assets-retry/tree/master/examples/webpack)里的，不要直接 import。如果仍有问题，麻烦提供一下能够复现的 demo
