### ISSUE TITLE
css文件的加载是否需要和js一样，有异步加载的处理

### ISSUE THREAD

**Issue by ycvcb123** [Nikaple/assets-retry#74]
![image](https://user-images.githubusercontent.com/15381888/96529810-a404ea00-12b8-11eb-9a31-06d223af7f6a.png)
引入到项目中以后发现一个问题，如上图，css的加载也有resolve和reject的处理，会导致项目报错，这个是不是也要和js一样做async的处理？

**Comment by Nikaple** [comment]
抱歉回复慢了，欢迎PR
