### ISSUE TITLE
支持安卓5.0吗 试了下好像有问题

### ISSUE THREAD

**Issue by sunbinbin007** [Nikaple/assets-retry#76]

**Comment by Nikaple** [comment]
https://automate.browserstack.com/dashboard/v2/public-build/RW5ISklMVUg1WlI2RGxCcllROXdOWmRuS1lITE02aUV2YXhWK2ROM05adz0tLXNrLzNMU3dSK3lod0pEbW1LUG4xbkE9PQ==--ce31c9e3015315c7aa4735e5976d047f9dc80eba

自动化测试覆盖了 Android 4.4、Android 9.0 等，并没有问题，如果 5.0 有问题可以具体描述下。
