### ISSUE TITLE
about defer

### ISSUE THREAD

**Issue by ycj1905** [Nikaple/assets-retry#79]
Hello I wanna know is this lib can confirm the scripts with `defer` attribute will works the same as browser default behavior ?

- origin with order
1. cdn1/a.js (200)
2. cdn1/b.js (403)
3. cdn1/c.js (200)

- expected browser excecution order
1. cdn1/a.js (200)
2. cdn1/b.js (403) -> 3. cdn2.b.js
4. cdn1/c.js (200)

**Comment by Nikaple** [comment]
> 2.cdn1/b.js (403) -> 3. cdn2.b.js

Did you suggest that the correct order for this situation is `a.js` -> `c.js` -> `b.js`?

Like this:

1. cdn1/a.js (200)
2. cdn1/b.js (403) -> 4. cdn2/b.js
3. cdn1/c.js (200)

This is actually true, as `c.js` will always be executed after `a.js`. And for `b.js` which is inserted into DOM tree at runtime, the `defer` attribute will be retained, so `b.js` will be garenteed to be executed after `c.js`.

Feel free to re-open the issue if this doesn't explain.
