### ISSUE TITLE
retryTimes问题

### ISSUE THREAD

**Issue by HughDai** [Nikaple/assets-retry#81]
在vue单页项目或者单个页面有多个相同资源请求的情况下，retryTimes超过maxRetryCount时被视为fail，导致资源不会重试。
```html
<img src="http://cdn.a.com/img/1.png">
<img src="http://cdn.a.com/img/1.png">
<img src="http://cdn.a.com/img/1.png">
```
在单页应用中，在路由来回切换过程中 ```currentCollector['/img/1.png']```的retryTimes属性会累加，导致超过maxRetryCount，然后之后的```/img/1.png```不会被重试

**Comment by Nikaple** [comment]
因为现在数据统计是URL维度的，确实会存在这样的问题。不过如果要解决的话，在现有数据格式定义的框架下不太好改，不知道有没有好的建议呢？如果直接将不同的 Element 看作不同的资源，那么势必会导致数据统计对象有破坏性变更，例如给每个元素增加唯一ID：
```js
{
  "/img/1.png_n4xF": { /* ... */ },
  "/img/1.png_1H8z": { /* ... */ },
}
```

如果只是单纯向解决 SPA 中图片不会重试的问题，我个人倾向于在路由切换的时候，直接将 stat 中记录的数据全部清空。例如：

```js
// 如果是 hash 路由
window.addEventListener('hashchange', () => {
  Object.values(window.assetsRetryStatistics).forEach(value => { value.retryTimes = 0 })
})
```

**Comment by HughDai** [comment]
按照现有代码的逻辑，是在errorHandler给元素添加唯一ID，同时存在多个相同资源的情况下还是会存在有一个元素请求的资源不会重试的情况。只是单纯向解决 SPA 中图片不会重试的问题，我的解决方案是在onFail和onSuccess时把对应的retryTimes重新置为0。
