### ISSUE TITLE
How to ensure the correctness of loading order on IE / Edge?

### ISSUE THREAD

**Issue by elvinn** [Nikaple/assets-retry#83]
In `src/util.ts`, I found `doc.write()` is only used when the browser is not IE or Edge.

In IE or Edge, the library appends  script  to head element, the loading order may be wrong?

![image](https://user-images.githubusercontent.com/28722527/137686334-aeca7c90-9184-4e54-91ca-874e303d249f.png)

**Comment by Nikaple** [comment]
There is indeed such a problem. At present, there is no good way to ensure the loading order of script tags in Edge/IE. However, the `assets-retry` library was originally designed for extreme situations (such as domain names that cannot be resolved), and the share of these browsers is negligible (Edge + IE ≈ 5%), so the users affected by this issue should be relatively low (1/million in our case).
