### ISSUE TITLE
createHookedElement 为什么返回了一个代理对象，而不是在源对象上代理方法

### ISSUE THREAD

**Issue by FrankPaul1** [Nikaple/assets-retry#84]
请问下，在 retry-async 中的 createHookedElement 是返回了一个新构造的代理对象 $hookedElement：
![image](https://user-images.githubusercontent.com/9024308/144195669-619968c2-718d-4ae2-8d8e-7fefa437abcd.png)
为此，还需要 hack Node 和 Element （hookPrototype） 来识别新的对象；

另一种做法是在源对象上代理 onload，onerror 和 addEventListener，这样似乎就不需要 hack Node 和 Element 了。

采用返回新对象的方式有什么特别的考虑吗？

**Comment by Nikaple** [comment]
如何代理 onload, onerror 呢，有更好的实现方式吗？

**Comment by FrankPaul1** [comment]
例如直接对 $element 做代理：
```
Object.defineProperties($element, descriptors);
return $element;
```

**Comment by Nikaple** [comment]
这段代码时间有点久了不太记得这么写的原因了💦 如果有 BUG 可以提新 issue，有好建议欢迎 PR 哈
