### ISSUE TITLE
css 背景图的 important 能去掉么？

### ISSUE THREAD

**Issue by mrbone** [Nikaple/assets-retry#85]
![image](https://user-images.githubusercontent.com/2182349/158739138-8340a67f-6d67-432b-aa6a-52f21a233152.png)
导致所有 background-image 都会带上 important，theme 场景下需要复写的话就要增加 css 权重，当时这个考虑是为了兼容 IE9？

**Comment by Nikaple** [comment]
有点记不清这里为什么要用 `!important` 了，可以先用 PR 里的版本，加上 `styleImageNoImportant: true` 参数试试
