### ISSUE TITLE
同步捕获错误，重载到最大retryTimes后，异步捕获还会动态插入一次，导致重载次数有问题

### ISSUE THREAD

**Issue by shinelp100** [Nikaple/assets-retry#89]
https://github.com/Nikaple/assets-retry/blob/a1dc84f86070041375eaa53605341f9ed4c84c9e/src/retry-async.ts#L117

**Comment by Nikaple** [comment]
请详细描述以下信息：

### 当前表现

### 预期表现

### 复现步骤


如需 Demo，可参考以下链接
重试一次：https://nikaple.com/assets-retry/vue/?retryTimes=1#/
重试两次：https://nikaple.com/assets-retry/vue/?retryTimes=2#/

window.assetsRetryStatistics 保存了重试的数据，没看出有什么问题

**Comment by shinelp100** [comment]
大佬，这边问题找到，是由于我这边错误修改retry-sync中`const isFinalRetry = currentCollector[retryTimesProp] > opts[maxRetryCountProp]`这块逻辑(>=)造成的。与框架本身无关。

**Comment by shinelp100** [comment]
大佬还有个问题，对于css样式重载成功后，如果css域名非当前页面域名，并未添加`crossorigin="anonymous"`属性的情况下，rules获取始终是null，直接return，未调用callOnSuccess()，造成数据统计上的一些问题。
```javascript
const rules = getCssRules(targetStyleSheet)
        if (rules === null) {
            return
}
```
        
我这边简单粗暴地添加了一次非当前域名时 调用一次 callOnSuccess。这边如何要做一下优雅处理呢?【插入的css添加`crossorigin="anonymous"`会导致跨域问题】
```javascript
const rules = getCssRules(targetStyleSheet)
        if (rules === null) {
             if(currentDomain && win.location.href.indexOf(currentDomain) === -1){
                // fix跨域脚本加载报错问题 referer: https://stackoverflow.com/questions/49993633/uncaught-domexception-failed-to-read-the-cssrules-property
                callOnSuccess()
        }
            return
}
```

**Comment by Nikaple** [comment]
如果CSS在非你可控的域名上，建议直接在 `onRetry` 中忽略。如果CSS在你可控的域名上，建议增加跨域头。
