### ISSUE TITLE
加载下一个资源时如何重置使用的 domain？

### ISSUE THREAD

**Issue by moecasts** [Nikaple/assets-retry#90]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
当上一个资源重试后，会永久性的改变使用的 domain，导致下一个资源也是使用该 domain.

![image](https://user-images.githubusercontent.com/37169906/174344559-1c528c4e-6c22-491a-8f87-360230e7aeff.png)

## Expected behavior
每次加载新的资源都重置使用的 domain，从第一个 domain 开始加载，不然可能 cdn 只是少了一个文件，导致后面的资源都用不了该 cdn 地址。

## What is the motivation / use case for changing the behavior?
可能 cdn 只是少了一个文件，导致后面的资源都用不了该 cdn 地址。

## Environment

<pre><code>
Assets-retry version: 0.3.2

</code></pre>

**Comment by Nikaple** [comment]
请提供一个[最小复现示例](http://minimum-reproduction.wtf)来帮助复现并定位问题

**Comment by moecasts** [comment]
经测试，这是偶发情况，先关闭了。
