### ISSUE TITLE
偶现情况: hookElement 出来的不是 Node，导致 appendChild 的时候出错。

### ISSUE THREAD

**Issue by moecasts** [Nikaple/assets-retry#91]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
hookElement 出来的不是 Node，导致 appendChild 的时候出错。
```
{
  "message":"Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.",
  "name":"TypeError",
  "stack":"TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.\n"
}
```

## Expected behavior
能确保 hookElement 出来的一定是 Node.

## Minimal reproduction of the problem with instructions
偶现情况，暂未找到原因

## What is the motivation / use case for changing the behavior?
不会阻塞其他脚本的加载

## Environment

<pre><code>
Assets-retry version: 0.3.3

 
For Tooling issues:
- Browser version: Edge(103.0)
- Platform:  Windows

Others:
- userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37

</code></pre>

**Comment by Nikaple** [comment]
请提供一个[最小复现示例](http://minimum-reproduction.wtf)来帮助复现并定位问题

（可以在报错前断点看看，有可能是你传递给appendChild的参数真的不是Node类型）

**Comment by moecasts** [comment]
@Nikaple 目前无法复现，所以想来这里问一下，出错的 `appendChild` 是 `webpack` 里的那个动态加载的 `createElement('script')`。经过 `hookElement` 之后这个元素的返回值是 `hookedElement`。

**Comment by Nikaple** [comment]
> 出错的 `appendChild` 是 `webpack` 里的那个动态加载的 `createElement('script')`。经过 `hookElement` 之后这个元素的返回值是 `hookedElement`。

这是为了重试动态加载 JS 而执行的正常逻辑。

**Comment by moecasts** [comment]
> 这是为了重试动态加载 JS 而执行的正常逻辑。

嗯嗯，我理解，不过根据报错，像是有某种情况 hook 失败了，导致的 `Failed to execute 'appendChild' on 'Node'`

**Comment by Nikaple** [comment]
所以需要你提供复现链接，或者定位到问题的原因，只提一个issue并不能解决问题

**Comment by moecasts** [comment]
目前就是无法稳定复现，所以来这里提 issue 看看有没有啥头绪的，等找到稳定复现的情况再继续这个 issue 吧。

**Comment by DillionZ** [comment]
> 目前就是无法稳定复现，所以来这里提 issue 看看有没有啥头绪的，等找到稳定复现的情况再继续这个 issue 吧。

老哥，你解决了吗？我也遇到了这个问题。

**Comment by moecasts** [comment]
> 老哥，你解决了吗？我也遇到了这个问题。

还没解决。

**Comment by WinneyFeng** [comment]
hi @Nikaple 返回的却是不是Node,可以用下面代码稳定重现。如果script不再retry domian list里面能不能直接走原生的document create？
`<script>
window.intercomSettings = {};
(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',w.intercomSettings);}else{var d=document;var i=function(){i.c(arguments);};i.q=[];i.c=function(args){i.q.push(args);};w.Intercom=i;var l=function(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/{{intercomKey}}';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);};if(document.readyState==='complete'){l();}else if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();
</script>
`

**Comment by WinneyFeng** [comment]
hi @Nikaple 我们找到了百分百复现的步骤，你这边最近会修复吗？
复现代码：
`<script>
var iframe = document.createElement('iframe');
iframe.src = 'about:blank';
document.body.appendChild(iframe);
iframe.addEventListener('load', function() {
    // !!! NOTE: 这一行如果改成 var script = iframe.contentDocument.createElement('script'); 就不会有问题
    var script = document.createElement('script');
    script.src = 'https://example.com/your-script.js';
    iframe.contentDocument.head.appendChild(script);
});
</script>
`

**Comment by Nikaple** [comment]
@DillionZ @moecasts @WinneyFeng 有空可以尝试下 #103 是否解决问题：https://github.com/Nikaple/assets-retry/tree/fix/iframe/dist

**Comment by WinneyFeng** [comment]
> @DillionZ @moecasts @WinneyFeng 有空可以尝试下 #103 是否解决问题：https://github.com/Nikaple/assets-retry/tree/fix/iframe/dist

hi @Nikaple 上一次提供的最小复现代码是fixed了，但是我这边的页面代码还是可以百分百复现，于是再给你提供一个最小复现代码：
`<script>
	var iframe = document.createElement('iframe');
	iframe.src = 'about:blank'; document.body.appendChild(iframe);
	var script = document.createElement('script'); script.src = '/assets/plugins/storehub-frontend-utils/frontend-utils.2.0.4.umd.production.min.js';
	iframe.contentDocument.head.appendChild(script); 
</script>`

**Comment by Nikaple** [comment]
在iframe中append父页面document创建的HTML标签这种场景过于小众，且修复成本很高，暂不考虑支持了
