### ISSUE TITLE
异步脚本加载超时没有重试

### ISSUE THREAD

**Issue by moecasts** [Nikaple/assets-retry#95]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
异步脚本加载超时没有触发重试机制。
<img width="522" alt="image" src="https://user-images.githubusercontent.com/37169906/194988451-46dde928-5af3-4cf9-a28b-e866b9a21d97.png">

## Expected behavior
当异步脚本加载超时也能触发重试机制。

## Minimal reproduction of the problem with instructions
使用 whistle 延迟脚本加载时长。
```
xxx reqDelay://180000
```
FYI: https://wproxy.org/whistle/rules/reqDelay.html

## Environment

<pre><code>
Assets-retry version: 0.3.3

 
For Tooling issues:
- Browser version: Chrome 105.0.5195.125
- Platform:  Mac

Others:

</code></pre>

**Comment by Nikaple** [comment]
assets-retry 是通过劫持 script 标签的 onload, onerror 事件来实现重试的，由于超时场景下 onload, onerror 均不会触发，所以无法实现超时脚本的自动重试
