### ISSUE TITLE
使用 js 动态添加/移除 style 标签，style 元素无法被 GC

### ISSUE THREAD

**Issue by jiezi19971225** [Nikaple/assets-retry#96]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
使用 js 动态添加/移除 style 标签
style 标签会变成 Detached Element 无法被 GC 造成内存泄漏

![image](https://user-images.githubusercontent.com/24801265/198562283-5a9b2a26-080d-468f-a3b6-0014000f1e5a.png)
使用 Edge 的 Detached Elements 分析，调用 removeChild 将 style 移除后，style 标签变成 Detached Element
![image](https://user-images.githubusercontent.com/24801265/198562150-b889e5fb-fe3a-4a67-b8e2-2ea10f7a5b09.png)

## Expected behavior
style 标签被 remove 后可以被正确 GC

## Minimal reproduction of the problem with instructions

执行以下代码
<pre><code>
    let styleElement: any = document.createElement('style')
    document.body.appendChild(styleElement)
    setTimeout(() => {
      document.body.removeChild(styleElement)
      styleElement = undefined
    }, 1000)
</code></pre>

可以使用 Edge 浏览器的 Detached Elements 确认
![image](https://user-images.githubusercontent.com/24801265/198564130-26db6545-0fb1-41c6-8d92-0ef9e4fdc90c.png)

## Environment

<pre><code>
Assets-retry version: 0.3.3

 
For Tooling issues:
- Browser version: Microsoft Edge 107.0.1418.24  
- Platform:  Mac

Others:

</code></pre>

查看源码发现 retry-css.ts 中， handledStylesheets 缓存了 style 标签的引用，当 style 标签移除时，没有清理这里的缓存，这里还保留引用导致无法被 GC

**Comment by Nikaple** [comment]
这里有少量的style标签不被GC感觉问题也不大？毕竟一般网页也不会有超过10个style标签吧。如果要解决GC问题，可能得引入WeakMap，在包体积上感觉有点得不偿失？

**Comment by jiezi19971225** [comment]
感谢大佬回复，我这边的场景可能有些特殊 是在 vue2 下动态增加 style 标签
```
<component :is="'style'">{{ injectStyle }}</component>
```
style 标签没被 GC，导致了整个 vue 实例都没有被 GC，这样内存泄漏就比较严重了

然后要解决的话，感觉也可以在每次更新 style 缓存的时候 document.documentElement.contains 判断下，不在 dom 树中就删掉吧

**Comment by Nikaple** [comment]
可以尝试一下 #97 是否能解决问题

**Comment by jiezi19971225** [comment]
> 可以尝试一下 #97 是否能解决问题

可以，完美解决
