### ISSUE TITLE
大佬几时发布新版本呢？

### ISSUE THREAD

**Issue by waldenlden** [Nikaple/assets-retry#99]
<img width="1210" alt="企业微信截图_e60af67c-051a-46bc-ab23-804f1a7743ed" src="https://user-images.githubusercontent.com/65232575/210969559-6608f699-ade5-47fd-9f6e-e2ba04908ed9.png">
I would like to ask this fix related to css, when will the author plan to release it?

**Comment by Nikaple** [comment]
published v0.3.4 to npm
